# Generated by Django 2.2.7 on 2019-11-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='data',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='data',
            new_name='date',
        ),
    ]
